name: CI

on:
  pull_request:
  push:
    branches: [master, dev]

defaults:
  run:
    shell: bash

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        cabal: ["latest"]
        ghc:
          - "8.6.5"
          - "8.8.4"
          - "8.10.3"

    steps:
    - uses: actions/checkout@v2
      name: Checkout base repo
    - uses: haskell/actions/setup@v1
      id: haskell-setup
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - uses: actions/checkout@v2
      name: Get cabal-extras
      with:
        repository: phadej/cabal-extras
        path: ./cabal-extras
    - name: Configure main repo
      run: cabal new-configure --flags="dev"
    - name: Configure cabal-docspec
      working-directory: cabal-extras/cabal-docspec
      run: cabal new-configure -w ${{ steps.haskell-setup.outputs.ghc-exe }}
    - name: Freeze
      run: |
        cabal freeze
        (cd ./cabal-extras/cabal-docspec && cabal freeze)
    - uses: actions/cache@v2.1.3
      name: Cache
      with:
        path: |
          ${{ steps.haskell-setup.outputs.cabal-store }}
          dist-newstyle
          ./cabal-extras/cabal-docspec/dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze', './cabal-extras/cabal-docspec/cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}-
    - name: Install base dependencies
      run: cabal new-build --only-dependencies --flags="dev"
    - name: Install cabal-docspec
      working-directory: cabal-extras/cabal-docspec
      run: cabal new-install --install-method=copy --installdir=${{ runner.temp }} --overwrite-policy=always
    - name: Build base repo
      run: |
        cabal new-build --flags="dev" || { # macOS + TH = QQ
          cabal clean && cabal new-build --flags="dev"
        }
    - name: Run doctests
      run: ${{ runner.temp }}/cabal-docspec -v --trace-process --timeout 30 --strip-comments --builddir "${{ github.workspace }}/dist-newstyle"
