name: CI

on:
  pull_request:
  push:
    branches: [master, dev]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        cabal: ["latest"]
        ghc:
          - "8.6.5"
          - "8.8.4"
          - "8.10.3"

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      id: haskell-setup
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
   
    - name: Update
      run: cabal new-update
    - name: Configure
      run: cabal new-configure --flags="dev"
    - name: Freeze
      run: cabal freeze
    - uses: actions/cache@v2.1.3
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.haskell-setup.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
    - name: Install-dependencies
      run: cabal new-build --only-dependencies --flags="dev"
    - name: Build
      run: cabal new-build --flags="dev"

