name: CI

on:
  pull_request:
  push:
    branches: [master, dev]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        cabal: ["latest"]
        ghc:
          - "8.6.5"
          - "8.8.4"
          - "8.10.3"

    steps:
    - uses: actions/checkout@v2
      name: Checkout base repo
    - uses: haskell/actions/setup@v1
      id: haskell-setup
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    - uses: actions/checkout@v2
      name: Get cabal-extras
      with:
        repository: phadej/cabal-extras
        path: ./cabal-extras
    - name: Update
      run: cabal new-update
    - name: Configure main repo
      run: cabal new-configure --flags="dev"
    - name: Configure cabal-docspec
      run: |
        cd ./cabal-extras/cabal-docspec
        ${{ steps.haskell-setup.outputs.cabal-exe }} new-configure -w ${{ steps.haskell-setup.outputs.ghc-exe }}
    - name: Freeze
      run: cabal freeze
    - uses: actions/cache@v2.1.3
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.haskell-setup.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
    - name: Install base dependencies
      run: cabal new-build --only-dependencies --flags="dev"
    - name: Install cabal-docspec
      run: |
        cd ./cabal-extras/cabal-docspec
        ${{ steps.haskell-setup.outputs.cabal-exe }} new-install -w ${{ steps.haskell-setup.outputs.ghc-exe }}
    - name: Build base repo
      run: cabal new-build --flags="dev"
    - name: Run doctests
      run: ${{ steps.haskell-setup.outputs.cabal-store }}/bin/cabal-docspec -w ${{ steps.haskell-setup.outputs.ghc-exe }}

